version: '3.8'

services:
  your-api:
    container_name: your-api
    image: ghcr.io/yourrepo/your-api:latest
      #ports:
      #- "4187"
    env_file:
      - ./.env
    depends_on:
      - qdrant
      - rabbitmq
    networks:
      - your-network

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
      #ports:
      #- "6333"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - your-network

  minio:
    container_name: minio
    image: minio/minio
    command: server /data --console-address ":9001"
      #ports:
      #- "9000" # server
      #- "9001" # ui
    volumes:
      - minio-data:/data
    networks:
      - your-network
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

  postgres:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - your-network
        #ports:
        #- "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
      #ports:
      #- "5672"
      #- "15672"
    networks:
      - your-network
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  mongo:
    container_name: mongo
    image: mongo
      #ports:
      #- "27017"
    networks:
      - your-network
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # ports:
    #   - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    environment:
      - PROMETHEUS_USERNAME=${PROMETHEUS_USERNAME}
      - PROMETHEUS_PASSWORD=${PROMETHEUS_PASSWORD}
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - your-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    # ports:
    #   - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    networks:
      - your-network

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  qdrant-data:
    driver: local
  minio-data:
    driver: local
  postgres-data:
    driver: local
  mongo-data:
    driver: local

networks:
  your-network:
    external: true